name: estudos
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  package_info_plus: ^8.0.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/profileImages/
    - assets/bebaralho-cearense/
    - assets/bebaralho-br/
    - assets/hipoteticamente/
    - assets/capa-bebaralho-cearense.png
    - assets/capa-hipoteticamente.png
    - assets/capa-bebaralho-br.png
    - assets/app_icon.png
    - assets/icone_imagem.png
    - assets/videos/opening-video.mp4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
